CursosAgentes/Controllers/CursosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CursosAgentes.Models;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System.IO;
using System.Net;
using System.Net.NetworkInformation;
using System.Text;
using System.Text.RegularExpressions;
using log4net;
using CursosAgentes.Contextos;
using CursosAgentes.Resources;
using System.Globalization;
using System.Threading;

namespace CursosAgentes.Controllers
{
    public class CursosController : BaseController
    {
        private static readonly ILog Log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);


        CursosUsuarios usu = new CursosUsuarios();
        CursosCursos curs = new CursosCursos();
        CursosCursos_Usuarios curs_usu = new CursosCursos_Usuarios();
        CursosDocumentaciones doc = new CursosDocumentaciones();
        CursosTexts text = new CursosTexts();
        CursosPreguntas preg = new CursosPreguntas();
        CursosPuntuaciones_Preguntas punt_resp = new CursosPuntuaciones_Preguntas();
        CursosPuntuaciones punt = new CursosPuntuaciones();
        CursosRespuestas resp = new CursosRespuestas();
        DateTime fechahora = DateTime.Now;
        AgentesUsuarios ag = new AgentesUsuarios();
        ComercialesAgentes usu_com = new ComercialesAgentes();
        CursosHistorico curs_histo = new CursosHistorico();
        string contexto = string.Empty;
        
        static string enlaceAgente;

        public ActionResult Index(string dni, string usuario, string password)
        {

            dni = dni.Trim();
            usuario = usuario.Trim();
            password = password.Trim();

            if (Session["contexto"] == null)
            {

                ag = ManagerService.FindByDniPhonePasswordAgente(dni, usuario, password, out string contexto);

                if (!string.IsNullOrEmpty(contexto))
                    Session["contexto"] = contexto;
            }
            else {

                contexto = Session["contexto"].ToString();
                ag = ManagerService.FindByDniPhonePasswordAgenteDirect(dni, usuario, password, contexto);
                if (ag == null) {
                    Session.Abandon();
                    return RedirectToAction("Index","Home");
                }
            }

            if (string.IsNullOrEmpty(contexto))
            {
                if (Session["contexto"] != null)
                    contexto = Session["contexto"].ToString();
            }



            if (ag != null) {

                curs_usu = ManagerService.GetContext(contexto).CursosCursos_Usuarios.Where(x => x.ID_USUARIOS == ag.id_usuarios).FirstOrDefault();

                if (curs_usu == null)
                {
                    curs_usu = new CursosCursos_Usuarios();
                    curs_usu.ID_USUARIOS = ag.id_usuarios;
                    curs_usu.ID_CURSOS = 1;

                    ManagerService.GetContext(contexto).CursosCursos_Usuarios.Add(curs_usu);
                    ManagerService.GetContext(contexto).SaveChanges();

                    Session["idUsuario"] = ag.id_usuarios;
                    Session["nombreUsuario"] = ag.Login;

                    listarCursos();
                    listarCursosUsuarios();
                    listarAgentesUsuario();
                    listarComercialesAgentes();
                    listarUsuarios();

                    CursosController.enlaceAgente = "https://grupotitanes.es:8555/Cursos/Cursos/Index/" + ag.Documento + "/" + ag.Login + "/" + ag.Documento;

                    return View();
                }
                else
                {
                    ag = ManagerService.GetContext(contexto).AgentesUsuarios.Where(x => x.id_usuarios == curs_usu.ID_USUARIOS).FirstOrDefault();
                    if (ag.CursoRealizado.HasValue) {
                        DateTime fechaCaduca = (DateTime)ag.CursoRealizado;
                        fechaCaduca = fechaCaduca.AddDays(350);
                        if (fechaCaduca < fechahora)
                        {
                            punt = ManagerService.GetContext(contexto).CursosPuntuaciones.Where(X => X.ID_USUARIOS == curs_usu.ID_USUARIOS && X.ID_TEXTS == 1).FirstOrDefault();
                            if (punt != null)
                            {
                                ManagerService.GetContext(contexto).CursosPuntuaciones.Remove(punt);
                            }
                            curs_usu.ESTADO = null;

                            ManagerService.GetContext(contexto).SaveChanges();
                        }
                    }


                    Session["idUsuario"] = ag.id_usuarios;
                    Session["nombreUsuario"] = ag.Login;

                    listarCursos();
                    listarCursosUsuarios();
                    listarAgentesUsuario();
                    listarComercialesAgentes();
                    listarUsuarios();

                    CursosController.enlaceAgente = "https://grupotitanes.es:8555/Cursos/Cursos/Index/" + ag.Documento + "/" + ag.Login + "/" + ag.Documento;


                    return View();
                }
            }
            else {
                return RedirectToAction("Index", "Home");
            }

        }

        public ActionResult IndexProspecto(int idProspecto) {

            if (Session["contexto"] != null)
                contexto = Session["contexto"].ToString();

            curs_usu = ManagerService.GetContext(contexto).CursosCursos_Usuarios.Where(x => x.ID_PROSPECTO == idProspecto).FirstOrDefault();

            if (curs_usu == null)
            {
                curs_usu = new CursosCursos_Usuarios();
                curs_usu.ID_PROSPECTO = idProspecto;
                curs_usu.ID_CURSOS = 1;

                ManagerService.GetContext(contexto).CursosCursos_Usuarios.Add(curs_usu);
                ManagerService.GetContext(contexto).SaveChanges();

                System.Web.HttpContext.Current.Session["prospecto"] = idProspecto;

                return RedirectToAction("accederText", new { id = 1 });
            }
            else if (curs_usu.ESTADO == 1)
            {
                return Content("<script>alert('"+ CursosAgentesResources.CourseAvailable + "');window.location.href = '/Cursos/Home/Index';</script>");
            }
            else {
                System.Web.HttpContext.Current.Session["prospecto"] = idProspecto;

                return RedirectToAction("accederText",new { id=1});
            }
        }

        [HttpPost]
        public ActionResult Documentacion()
        {

            if (string.IsNullOrEmpty(contexto))
            {
                if (Session["contexto"] != null)
                    contexto = Session["contexto"].ToString();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

            if ((int)System.Web.HttpContext.Current.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                listarCursos();
                listarCursosUsuarios();

                string idCurso = Request.Form["idCurso"];
                List<CursosDocumentaciones> listDocs = ManagerService.GetContext(contexto).CursosDocumentaciones.ToList();

                foreach (var list in listDocs)
                {
                    if (list.ID_CURSO == Int32.Parse(idCurso))
                    {
                        ViewBag.urlDoc = list.URL;
                    }
                }


                return View();
            }

        }

        public ActionResult listarCursosUsuarios()
        {
            List<CursosCursos_Usuarios> listaCursosUsuarios = ManagerService.GetContext(contexto).CursosCursos_Usuarios.ToList();
            ViewBag.listaCursosUsuarios = listaCursosUsuarios;

            return View();
        }

        public ActionResult listarAgentesUsuario()
        {
            List<AgentesUsuarios> listaAgentesUsuarios = ManagerService.GetContext(contexto).AgentesUsuarios.ToList();
            ViewBag.listaAgentesUsuarios = listaAgentesUsuarios;

            return View();
        }

        public ActionResult listarComercialesAgentes()
        {
            List<ComercialesAgentes> listaComercialesAgentes = ManagerService.GetContext(contexto).ComercialesAgentes.ToList();
            ViewBag.listaComercialesAgentes = listaComercialesAgentes;

            return View();
        }

        public ActionResult listarDocmentaciones()
        {
            List<CursosDocumentaciones> listaDocumentaciones = ManagerService.GetContext(contexto).CursosDocumentaciones.ToList();
            ViewBag.listaDocumentaciones = listaDocumentaciones;

            return View();
        }
        public ActionResult listarText()
        {
            List<CursosTexts> listaText = ManagerService.GetContext(contexto).CursosTexts.ToList();
            ViewBag.listaText = listaText;

            return View();
        }

        public ActionResult listarCursos()
        {
            List<CursosCursos> listaCursos = ManagerService.GetContext(contexto).CursosCursos.ToList();
            ViewBag.listaCursos = listaCursos;

            return View();
        }

        public ActionResult listarRespuestas()
        {
            List<CursosRespuestas> listaRespuestas = ManagerService.GetContext(contexto).CursosRespuestas.ToList();
            ViewBag.listaRespuestas = listaRespuestas;

            return View();
        }

        public ActionResult listarPreguntas()
        {
            List<CursosPreguntas> listaPreguntas = ManagerService.GetContext(contexto).CursosPreguntas.ToList();
            ViewBag.listaPreguntas = listaPreguntas;

            return View();
        }

        public ActionResult listarPuntuaciones()
        {

CursosAgentes/Views/Cursos/Index.cshtml
@{
    List<CursosAgentes.Models.CursosUsuarios> listaUsuarios = ViewBag.listaUsuarios;
    List<CursosAgentes.Models.CursosCursos> listaCursos = ViewBag.listaCursos;
    List<CursosAgentes.Models.AgentesUsuarios> listaAgentesUsuarios = ViewBag.listaAgentesUsuarios;
}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>TITANES - @CursosAgentesResources.TrainingCourse</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <LINK href="~/Content/admin.css" rel="stylesheet" type="text/css">
    <style>

        a {
            text-decoration: none;
            color: black;
        }
        .contenido {
            margin-top: 50px;
            margin-bottom: 50px;
            border: 3px #ff8c00 solid;
            border-radius: 30px;
        }

        hr {
            width: 70%;
            border: 1px solid #ff8c00;
            border-radius: 30px;
        }

        .modal-content {
            background-color: lightgray;
        }

        .botonAcceder {
            background-color: #ff8c00;
            color: white;
        }
        .encabezadoTabla {
            background-color: #ff8c00;
            color: white;
        }
    </style>
</head>
<body>
    <div class="container-fluid">
        <div class="container contenido">
            <br />
            @if ((string)System.Web.HttpContext.Current.Session["contexto"]=="IT")
            {
                <img src="~/img/logoitaliano.jpg" width="25%" /><br /><br />
            }
            else
            {
                <img src="~/img/logo.jpg" width="25%" /><br /><br />
            }
            <h1 class="titulo-principal" style="color:#ff8c00"><b> @CursosAgentesResources.Courses</b></h1>
            <hr />
            <br /><br />

            @foreach (var usu in listaUsuarios)
            {
                if ((int)System.Web.HttpContext.Current.Session["idUsuario"] == usu.ID && usu.ADMIN == 1)
                {
                    <button class="btn btn-success" data-toggle="modal" data-target="#modal-crear-curso">Nuevo Curso +</button>
                    <br /><br />

                }

            }

            <table class="table table-hover tabla-actualizaciones">


                @foreach (var usu in listaUsuarios)
                {
                    if ((int)Session["idUsuario"] == usu.ID && usu.ADMIN == 1)
                    {

                        foreach (var list in listaCursos)
                        {

                            <thead class="encabezadoTabla">
                                <tr>
                                    <td class="col-id titulo-tabla"><b>NOMBRE</b></td>
                                    <td class="col-botones"></td>
                                </tr>
                            </thead>
                            <tr class="curso-@list.ID" id="todoscursos">
                                <td class="col-id titulo-tabla">
                                    <a href="~/Cursos/accederCurso/@list.ID"><b><i class="fa fa-graduation-cap" aria-hidden="true"></i>&nbsp;@list.NOMBRE </b></a>
                                </td>
                                <td class="col-botones">
                                    <div class="btn-group botones" role="group" aria-label="Basic example">

                                        <button type="button" class="btn btn-warning iconos-admin" data-toggle="modal" data-target="#modal-modificar-curso-@list.ID">Modificar</button>
                                        <button type="button" class="btn btn-danger iconos-admin" data-toggle="modal" data-target="#modal-eliminar-curso-@list.ID">Eliminar</button>

                                    </div>
                                </td>
                            </tr>



                            <!--MODAL CONFIRMACION ELIMINACION CURSO-->

                            <div class="modal" tabindex="-1" role="dialog" id="modal-eliminar-curso-@list.ID">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">

                                        <div class="modal-body" style="text-align:center">

                                            @using (Html.BeginForm("eliminarCurso", "Cursos", FormMethod.Post))
                                            {
                                                <h3>¿De verdad quieres eliminar el curso " @list.NOMBRE"?</h3>
                                                <br />
                                                <input type="text" class="form-control" id="id_curso" name="id_curso" value="@list.ID" style="display:none" />
                                                <button type="submit" class="btn botonAcceder">Si </button>
                                            }
                                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                                            <br /><br />
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <!--MODAL CONFIRMACION ELIMINACION CURSO-->

                            <!--MODAL MODIFICAR CURSO-->

                            <div class="modal" tabindex="-1" role="dialog" id="modal-modificar-curso-@list.ID">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title">Modificar Curso</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            @using (Html.BeginForm("modificarCurso", "Cursos", FormMethod.Post))
                                            {
                                                <div class="form-group " style="">
                                                    <label for="">Nombre</label><br />
                                                    <input type="text" class="form-control" id="nombre" name="nombre" /><br />
                                                    <input type="text" class="form-control" id="id_curso" name="id_curso" value="@list.ID" style="display:none" />


                                                </div>


                                                <div class="modal-footer">
                                                    <button type="submit" class="btn botonAcceder">Modificar</button>
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                                                </div>
                                            }

                                        </div>
                                    </div>
                                </div>
                            </div>

                            <!--MODAL MODIFICAR CURSO-->
                        }

                    }

                }

                @foreach (var ag in listaAgentesUsuarios)
                {
                    foreach (var list in listaCursos)
                    {
                        if (ag.id_usuarios == (int)Session["idUsuario"] && list.ID == 1)
                        {

                            <a href="@Url.Action("accederCurso", "Cursos",new { id=list.ID})">
                                <b><i class="fa fa-graduation-cap " aria-hidden="true"></i>&nbsp;@list.NOMBRE @DateTime.Today.Year</b>
                                <br /><br /><button class="btn botonAcceder">@CursosAgentesResources.DoCourse</button>
                            </a>


                        }

                    }
                }

            </table>

            <div onclick="javascript: window.location='@Url.Action("cerrarSession", "Home")'" style="cursor:pointer;margin-left:15px;">
                <br /><br /><h5 style="color:Red"> <i class="fa fa-arrow-circle-left" aria-hidden="true"></i>&nbsp;@CursosAgentesResources.LogOut</h5><br />
            </div>

            @foreach (var usu in listaUsuarios)
            {
                if ((int)Session["idUsuario"] == usu.ID && usu.ADMIN == 1)
                {
                    <div style="cursor:pointer;margin-left:15px">
                        <br /><br />
                        <h5> <i class="fa fa-arrow-circle-left" aria-hidden="true"></i>&nbsp;<a href="@Url.Action("cerrarSession", "Home")">@CursosAgentesResources.Back</a></h5><br />
                    </div>

                }
                else if ((int)Session["idUsuario"] == usu.ID && usu.AGENTE == 1)
                {
                    <div onclick="javascript: window.location='@Url.Action("cerrarSession", "Home")'" style="cursor:pointer;margin-left:15px;">
                        <br /><br /><h5 style="color:Red"> <i class="fa fa-arrow-circle-left" aria-hidden="true"></i>&nbsp;SALIR</h5><br />
                    </div>
                }
            }
        </div>
    </div>


    @foreach (var usu in listaUsuarios)
    {
        if ((int)Session["idUsuario"] == usu.ID && usu.ADMIN == 1)
        {
            <!--MODAL CREAR CURSO-->

            <div class="modal" tabindex="-1" role="dialog" id="modal-crear-curso">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">CREAR CURSO</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">

                            @using (Html.BeginForm("crearCurso", "Cursos", FormMethod.Post, new { enctype = "multipart/form-data" }))
                            {
                            <div class="form-group ">

                                <label for="">NOMBRE CURSO:</label><br />
                                <input type="text" class="form-control" name="nombre" required /><br />
                                <input type="text" class="form-control" id="id_curso" name="usuCrea" value="@Session["idUsuario"]" style="display:none" />
                                <label for="">NOMBRE TEMARIO:</label><br />
                                <input type="text" class="form-control" name="nombreTemario" required /><br />
                                <label for="">ADJUNTAR TEMARIO:</label><br />
                                <input type="file" class="form-control" name="urlProcedimiento" required />

                            </div>

                                <div class="modal-footer">
                                    <button type="submit" class="btn botonAcceder">Añadir</button>
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                                </div>
                            }

                        </div>
                    </div>
                </div>
            </div>

            <!--MODAL CREAR CURSO-->
        }
    }
        </body>
</html>

CursosAgentes/Views/Cursos/accederText.cshtml
@model CursosAgentes.Models.CursosTexts
@{
    List<CursosAgentes.Models.CursosRespuestas> listaRespuestasFiltrado = ViewBag.listaRespuestasFiltrado;
    List<CursosAgentes.Models.CursosPreguntas> listaPreguntasFiltrado = ViewBag.listaPreguntasFiltrado;
    List<CursosAgentes.Models.CursosCursos_Usuarios> listaCursosUsuarios = ViewBag.listaCursosUsuarios;
    List<CursosAgentes.Models.CursosDocumentaciones> listaDocumentaciones = ViewBag.listaDocumentaciones;
}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>TITANES - @CursosAgentesResources.TrainingCourse</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <LINK href="~/Content/admin.css" rel="stylesheet" type="text/css">
    <style>

        a {
            text-decoration: none;
            color: black;
        }

        .contenido {
            margin-top: 50px;
            margin-bottom: 50px;
            border: 3px #ff8c00 solid;
            border-radius: 30px;
        }

        hr {
            width: 70%;
            border: 1px solid #ff8c00;
            border-radius: 30px;
        }

        .modal-content {
            background-color: lightgray;
        }

        .botonAcceder {
            background-color: #ff8c00;
            color: white;
        }
        .td-10 {
            border-bottom:0px !important;
        }

    </style>
    <script>

    </script>
</head>
<body>
    <div class="container-fluid">
        <div class="container contenido">
            <br />
            @if ((string)System.Web.HttpContext.Current.Session["contexto"] == "IT")
            {
                <img src="~/img/logoitaliano.jpg" width="25%" /><br /><br />
            }
            else
            {
                <img src="~/img/logo.jpg" width="25%" /><br /><br />
            }
            <h1 class="titulo-principal" style="color:#ff8c00"><b>@Model.NOMBRE</b></h1>
            <hr />
            <br /><br />
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-right">

                    @using (Html.BeginForm("Documentacion", "Cursos", FormMethod.Post))
                    {
                        <button class="btn btn-outline-info" type="submit"><i class="fa fa-book" aria-hidden="true"></i>&nbsp;@CursosAgentesResources.Temary</button>
                        <input type="text" name="idCurso" value="@Model.ID_CURSO" style="display:none" />
                        <br /><br />
                    }
                </div>
            </div>

            @using (Html.BeginForm("insertarTextUsuario", "Cursos", FormMethod.Post))
            {

                <input type="text" name="id_curso" value="@Model.ID_CURSO" style="display:none" />
                <input type="text" name="text" style="display:none" value="@Model.ID" />
                <table style="width:100%">
                    @{
                        int contador = 1;


                    }
                    @foreach (var list in listaPreguntasFiltrado)
                    {
                        <tr>
                            <td>
                                <h5 style="padding-top:20px;padding-bottom:20px">@contador - @list.TEXTO</h5>
                                <input type="text" name="pregunta-@contador" style="display:none" value="@list.ID" />


                            </td>
                        </tr>


                        foreach (var resp in listaRespuestasFiltrado)
                        {
                            int cont = 0;
                            if (resp.ID_PREGUNTA == list.ID)
                            {
                                <tr style="text-align:left">

                                    <td>
                                        @foreach (var resp2 in listaRespuestasFiltrado)
                                        {
                                            if (resp2.CORRECTA == 1 && resp2.ID_PREGUNTA == list.ID)
                                            {
                                                cont = cont + 1;

                                            }
                                        }

                                        @if (cont == 2)
                                        {
                                            @:<input type="checkbox" name="respuesta-usu-@contador" value="@resp.ID" />&nbsp; @resp.TEXTO
                                            @:<input type="text" name="respuesta-@contador" value="@resp.ID" style="display:none" />
                                        }
                                        else
                                        {
                                            @:<input type="radio" name="respuesta-usu-@contador" value="@resp.ID" />&nbsp; @resp.TEXTO
                                            @:<input type="text" name="respuesta-@contador" value="@resp.ID" style="display:none" />
                                        }


                                    </td>

                                </tr>

                            }

                        }
                        <tr>

                            <td class="td-@contador" style="border-bottom:1px solid lightgrey;padding-bottom:50px !important"></td>
                        </tr>
                        contador = contador + 1;

                    }


                </table>

                <button class="btn botonAcceder" type="submit">@CursosAgentesResources.Deliver</button>

            }

        </div>
    </div>

</body>
</html>